#!/bin/bash -e
#
# S2I run script for the 'lighttpd-centos7' image.
# The run script executes the server that runs your application.
#
# For more information see the documentation:
#	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#
echo "---> Running your Node application ..."
if [ ! -z "${RUN_SCRIPT}" ]; then
	echo "---> Run script: ${RUN_SCRIPT}"
	eval "${RUN_SCRIPT}"
else
  echo "---> Running ..."
  exec npm start
fi